# Generated by Django 3.1.3 on 2020-11-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_details',
            fields=[
                ('user_id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='')),
                ('phone_no', models.TextField(max_length=10)),
                ('aadhar_no', models.TextField(max_length=12)),
                ('profile_type', models.CharField(choices=[('1', 'Job-seeker only'), ('2', 'Job-provider only'), ('3', 'both')], max_length=1)),
                ('skills', models.TextField(null=True)),
            ],
        ),
    ]
