# Generated by Django 3.1.3 on 2020-11-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_details',
            name='image',
            field=models.ImageField(upload_to='profile_pics/'),
        ),
    ]
