# Generated by Django 3.1.3 on 2020-11-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_details',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
