# Generated by Django 3.1.3 on 2020-11-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_job_details_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_details',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
