# Generated by Django 3.1.3 on 2020-11-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20201112_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_details',
            name='job_time',
            field=models.TimeField(),
        ),
    ]
